# Generated by Django 5.2.4 on 2025-07-22 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendance', to='classes.classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'classroom', 'date')},
        ),
    ]
